-- PLACE_OF_PERFORM_COUNTRY_CODE = "USA", COUNTRY_CODE = "USA"

CREATE TABLE fpds(
  piid                   VARCHAR(20) PRIMARY KEY, -- PIID
  agency_id              SMALLINT, -- CONTRACTING_AGENCY_ID (CONTRACTING_AGENCY_ID_1), FUNDING_AGENCY_ID, FUNDING_DEPARTMENT_ID, FUNDING_OFFICE_ID, CONTRACTING_OFFICE_ID
  agency_name            VARCHAR(50), -- CONTRACTING_AGENCY_NAME, FUNDING_AGENCY_NAME, FUNDING_DEPARTMENT_NAME, FUNDING_OFFICE_NAME, CONTRACTING_OFFICE_NAME
  product_code           INTEGER,  -- PRINCIPAL_NAICS_CODE
  product                VARCHAR(50), -- NAICS_DESCRIPTION
  award_type             VARCHAR(20), -- AWARD_TYPE_DESCRIPTION
  location_state_code    CHAR(2), -- LOCATION_STATE_CODE
  location_state_name    VARCHAR(50), -- LOCATION_STATE_NAME
  effective_date         DATE, -- EFFECTIVE_DATE


  is_sustainable         CHAR, -- CLAIMANT_PROGRAM, PLACE_OF_MANUFACTURE_DESC (MFG IN U.S., NOT A MANUFACTURED END PRODUCT), PRODUCT_OR_SERVICE_DESCRIPTION, RECOVERED_MATERIAL_CLS_DESC
  amount                 DOUBLE, -- TOTAL_OBLIGATED_AMOUNT, OBLIGATED_AMOUNT, CURRENT_CONTRACT_VALUE

);