drop table agencies;

CREATE TABLE agencies(
  agency_id              VARCHAR(20),
  abbreviation           VARCHAR(20),
  name                   VARCHAR(50));

INSERT INTO agencies(agency_id, abbreviation, name) VALUES
SELECT DISTINCT FUNDING_DEPARTMENT_ID, FUNDING_DEPARTMENT_NAME FROM fpds_small;


drop table fpds;

CREATE TABLE fpds(
  piid                   VARCHAR(100), -- PIID
  agency_id              VARCHAR(20), -- FUNDING_DEPARTMENT_NAME
  product                VARCHAR(100), -- PRODUCT_OR_SERVICE_DESCRIPTION
  location_state_code    CHAR(2), -- LOCATION_STATE_CODE
  effective_date         DATE, -- EFFECTIVE_DATE
  is_sustainable         CHAR, -- RECOVERED_MATERIAL_CLS_DESC (Exclude "no clauses included and sustainabi/lity includde")
  amount                 DOUBLE PRECISION); -- TOTAL_OBLIGATED_AMOUNT

INSERT INTO fpds(piid, agency_id, product, location_state_code, effective_date, is_sustainable, amount)
SELECT PIID,
       FUNDING_DEPARTMENT_ID,
       PRODUCT_OR_SERVICE_DESCRIPTION,
       LOCATION_STATE_CODE,
       to_date(EFFECTIVE_DATE, 'DD-Mon-YY'),
       CASE WHEN (RECOVERED_MATERIAL_CLS_DESC = 'NO CLAUSES INCLUDED AND NO SUSTAINABILITY INCLUDED') THEN 0 ELSE 1 END,
       CAST(TOTAL_OBLIGATED_AMOUNT AS DOUBLE PRECISION)
FROM fpds_small;

-- PLACE_OF_PERFORM_COUNTRY_CODE = "USA", COUNTRY_CODE = "USA"

CREATE TABLE fpds(
  piid                   VARCHAR(20) PRIMARY KEY, -- PIID
  agency_id              SMALLINT, -- CONTRACTING_AGENCY_ID (CONTRACTING_AGENCY_ID_1), FUNDING_AGENCY_ID, FUNDING_DEPARTMENT_ID, FUNDING_OFFICE_ID, CONTRACTING_OFFICE_ID
  agency_name            VARCHAR(50), -- CONTRACTING_AGENCY_NAME, FUNDING_AGENCY_NAME, FUNDING_DEPARTMENT_NAME, FUNDING_OFFICE_NAME, CONTRACTING_OFFICE_NAME
  product_code           INTEGER,  -- PRINCIPAL_NAICS_CODE
  product                VARCHAR(50), -- NAICS_DESCRIPTION
  award_type             VARCHAR(20), -- AWARD_TYPE_DESCRIPTION
  location_state_code    CHAR(2), -- LOCATION_STATE_CODE
  location_state_name    VARCHAR(50), -- LOCATION_STATE_NAME
  effective_date         DATE, -- EFFECTIVE_DATE


  is_sustainable         CHAR, -- CLAIMANT_PROGRAM, PLACE_OF_MANUFACTURE_DESC (MFG IN U.S., NOT A MANUFACTURED END PRODUCT), PRODUCT_OR_SERVICE_DESCRIPTION, RECOVERED_MATERIAL_CLS_DESC
  amount                 DOUBLE, -- TOTAL_OBLIGATED_AMOUNT       (, OBLIGATED_AMOUNT, CURRENT_CONTRACT_VALUE

);

CREATE SEQUENCE id_seq;
CREATE TABLE fpds_small (
  pk smallint NOT NULL DEFAULT nextval('id_seq'), PIID VARCHAR(200),CONTRACTING_AGENCY_ID VARCHAR(150), REF_IDV_PIID  VARCHAR(150),REF_IDV_AGENCY_ID  VARCHAR(150),MODIFICATION_NUMBER  VARCHAR(150),TOCP_SHORT_DESCRIPTION  TEXT,AWARD_TYPE_DESCRIPTION  VARCHAR(900),PRINCIPAL_NAICS_CODE  VARCHAR(150),NAICS_DESCRIPTION  VARCHAR(150),VENDOR_DUNS_NUMBER  VARCHAR(150),ORGANIZATION_TYPE  VARCHAR(150),DESCRIPTION_OF_REQUIREMENT  TEXT,URL  VARCHAR(150),CITY  VARCHAR(150),LOCATION_STATE_CODE  VARCHAR(150),LOCATION_STATE_NAME  VARCHAR(150),PLACE_OF_PERFORM_COUNTRY_CODE  VARCHAR(150),PLACE_OF_PERFORM_COUNTRY_NAME  VARCHAR(150),PLACE_OF_PERFORM_ZIP_CODE  VARCHAR(150),PLACE_CONGRESSIONAL_DISTRICT  VARCHAR(150),EFFECTIVE_DATE  VARCHAR(150),CURRENT_COMPLETION_DATE  VARCHAR(150),ULTIMATE_COMPLETION_DATE  VARCHAR(150),LAST_DATE_TO_ORDER  VARCHAR(150),SIGNED_DATE  VARCHAR(150),REASON_FOR_MODIFICATION_DESC  VARCHAR(150),TOTAL_OBLIGATED_AMOUNT  VARCHAR(150),OBLIGATED_AMOUNT  VARCHAR(150),CURRENT_CONTRACT_VALUE  VARCHAR(150),BASE_AND_ALL_OPTIONS_VALUE  VARCHAR(150),FUNDING_DEPARTMENT_ID  VARCHAR(150),FUNDING_DEPARTMENT_NAME  VARCHAR(150),FUNDING_AGENCY_ID  VARCHAR(150),FUNDING_AGENCY_NAME  VARCHAR(150),FUNDING_OFFICE_ID  VARCHAR(150),FUNDING_OFFICE_NAME  VARCHAR(150),CONTRACTING_AGENCY_ID_1  VARCHAR(150),CONTRACTING_AGENCY_NAME  VARCHAR(150),CONTRACTING_OFFICE_ID  VARCHAR(150),CONTRACTING_OFFICE_NAME  VARCHAR(150),REF_IDV_AGENCY_ID_1  VARCHAR(150),MULTIPLE_OR_SINGLE_AWARD_IDC  VARCHAR(150),TYPE_OF_IDC_DESC  VARCHAR(150),WHO_CAN_USE  VARCHAR(150),MAXIMUM_ORDER_LIMIT  VARCHAR(150),TYPE_OF_FEE_DESC  VARCHAR(150),FIXED_FEE_VALUE  VARCHAR(150),FEE_PAID_FOR_USE_OF_SERVICE  VARCHAR(150),ORDERING_PROCEDURE  VARCHAR(150),IDV_TYPE  VARCHAR(150),A76_DESC  VARCHAR(150),CLAIMANT_PROGRAM  VARCHAR(150),CLINGER_COHEN_ACT  VARCHAR(150),COMMERCIAL_ITEM_ACQUISTN_DESC  VARCHAR(150),COMMERCIAL_ITEM_TEST_PROGRAM  VARCHAR(150),SOLICITATION_PROCEDURES  VARCHAR(150),CONSOLIDATED_CONTRACT  VARCHAR(150),CONTINGENCY_OPS_DESC  VARCHAR(150),CONTRACT_BUNDLING_DESC  VARCHAR(150),CONTRACT_FINANCING_DESC  VARCHAR(150),CO_BUS_SIZE_DETERMINATION_DESC  VARCHAR(150),COST_ACCT_STANDARDS  VARCHAR(150),COST_OR_PRICING_DATA_DESC  VARCHAR(150),COUNTRY_CODE  VARCHAR(150),DAVIS_BACON_ACT_DESC  VARCHAR(150),VENDOR_DIVISION_NAME  VARCHAR(150),VENDOR_DIVISION_NUMBER  VARCHAR(150),EVALUATED_PREF_DESCRIPTION  VARCHAR(150),EXTENT_COMPETED_DESCRIPTION  VARCHAR(150),FED_BIZ_OPPS_DESC  VARCHAR(150),FOREIGN_FUNDING_DESC  VARCHAR(150),GFE_GFP_DESC  VARCHAR(150),IT_COMMERCIAL_ITEM_CAT_DESC  VARCHAR(150),CONTRACTING_AUTHORITY_DESC  VARCHAR(150),UNDEFINITIZED_ACTION_DESC  VARCHAR(150),LOCAL_AREA_SET_ASIDE  VARCHAR(150),MAJOR_PROGRAM_CODE  VARCHAR(150),PCARD_AS_PAYMENT_DESC  VARCHAR(150),MULTIYEAR_CONTRACT_DESC  VARCHAR(150),NATIONAL_INTEREST_DESCRIPTION  VARCHAR(150),NUMBER_OF_ACTIONS  VARCHAR(150),NUMBER_OF_OFFERS_RECEIVED  VARCHAR(150),OTHER_STATUTORY_AUTHORITY  VARCHAR(150),PERFORM_BASED_SERVICE_CONTRACT  VARCHAR(150),PLACE_OF_MANUFACTURE_DESC  VARCHAR(150),PRICE_EVAL_PERCENT_DIFF  VARCHAR(150),PRODUCT_OR_SERVICE_CODE  VARCHAR(150),PROGRAM_ACRONYM  VARCHAR(150),PRODUCT_OR_SERVICE_DESCRIPTION  VARCHAR(150),REASON_NOT_COMP_DESCRIPTION  VARCHAR(150),AGENCY_IDENTIFIER  VARCHAR(150),RECOVERED_MATERIAL_CLS_DESC  VARCHAR(150),RESEARCH_DESCRIPTION  VARCHAR(150),SEA_TRANSPORTATION_DESC  VARCHAR(150),SERVICE_CONTRACT_ACT_DESC  VARCHAR(150),SBC_DEMONSTRATION_PROGRAM  VARCHAR(150),SOLICITATION_ID  VARCHAR(150),SOLICITATION_PROC_DESCRIPTION  VARCHAR(150),STATRY_EXPTN_TO_FAIR_OPRTNTY  VARCHAR(150),SUBCONTRACT_PLAN_DESC  VARCHAR(150),SYSTEM_EQUIPMENT_CODE  VARCHAR(150),TYPE_OF_SET_ASIDE  VARCHAR(150),USE_OF_EPA_PRODUCTS_DESC  VARCHAR(150),WALSH_HEALEY_ACT_DESC  VARCHAR(150),TRANSACTION_NUMBER   VARCHAR(150)
);
ALTER SEQUENCE id_seq OWNED BY user.user_id;